services:
  - name: mssql-database
    type: private_service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SA_PASSWORD
        value: iits123
      - key: DB_NAME
        value: DiamondSoft

  - name: my-node-app
    type: web
    plan: free
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DB_HOST
        value: mssql-database
      - key: DB_USER
        value: sa
      - key: DB_PASSWORD
        value: iits123
      - key: DB_NAME
        value: DiamondSoft
      - key: DB_PORT
        value: "1433"
